### ISSUE TITLE
No module named 'nn_dataflow.Scheduling'

### ISSUE THREAD

**Issue by Timingan** [he-actlab/planaria.code#1]
As the title.
No such file found in 'nn_dataflow' document folder

**Comment by sgh7398** [comment]
Could you please let me know how you got into this error? The nn_dataflow.Scheduling is not used in the code actually... So you basically do not need it to get the Planaria simulator working

**Comment by Timingan** [comment]
Hi, 
Thanks for your reply and sorry for the missing details.
I tried to run the provided Jupyter Notebook codes and encountered this error when importing src.benchmarks.benchmarks (line 14).

Traceback (most recent call last):
    import src.benchmarks.benchmarks as benchmarks
  File "/planaria/src/benchmarks/benchmarks.py", line 8, in <module>
    from nn_dataflow import Network
  File "/planaria/nn_dataflow/__init__.py", line 36, in <module>
    from .NNDataflow import SchedulingResultDict
  File "/planaria/nn_dataflow/NNDataflow.py", line 28, in <module>
    from .Scheduling import SchedulingCondition, SchedulingResult, Scheduling
ModuleNotFoundError: No module named 'nn_dataflow.Scheduling'

**Comment by sgh7398** [comment]
Hi, Thanks for your detailed response, I have added the required file. Could you please pull one more time and try it out? Please let me know if you still have issues.

**Comment by Timingan** [comment]
Thanks!
