### ISSUE TITLE
Meaning of num_active_cores and num_cores

### ISSUE THREAD

**Issue by wtyytw0** [he-actlab/planaria.code#2]
Hi,

I am confused by the meaning of num_cores and num_active_cores in the config file. Is the meaning of num_cores same as number of sub-systolic array? Or does the  num_cores mean "number of PE in one sub-systolic  array"?

Thank you in advance
Taoyi

**Comment by sgh7398** [comment]
Hi,

The num_cores means the same as the number of subarrays definition according to the paper. The num_active_cores is used to model execution when a subset of systolic subarrays/cores are available due to co-location of multiple DNN inference executions.
